package com.system.reviewSystem.swagger.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.ApiInfoBuilder;
import springfox.documentation.service.ApiInfo;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spring.web.plugins.Docket;
import springfox.documentation.swagger2.annotations.EnableSwagger2;


@Configuration
@EnableSwagger2

public class SwaggerConfig {

    @Bean
    public Docket reviewApi() {


        return new Docket(DocumentationType.SWAGGER_2).groupName("com.system.reviewSystem").apiInfo(apiInfo()).select().build();
        //  .paths(regex("/users.*")).build();

    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder().title("Product API").description("reviewSystem API Documentation Generated by SWAGGER_2")
                .termsOfServiceUrl("").license("").licenseUrl("").version("1.0").build();
    }


}
